# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/la32r_soc_ciciec/rtl/ip/PLL_2019_2/clk_pll.xci
# IP: The module: 'clk_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/la32r_soc_ciciec/fpga/project/ipgen/clk_pll/clk_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/la32r_soc_ciciec/fpga/project/ipgen/clk_pll/clk_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/la32r_soc_ciciec/fpga/project/ipgen/clk_pll/clk_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/la32r_soc_ciciec/rtl/ip/PLL_2019_2/clk_pll.xci
# IP: The module: 'clk_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/la32r_soc_ciciec/fpga/project/ipgen/clk_pll/clk_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/la32r_soc_ciciec/fpga/project/ipgen/clk_pll/clk_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/la32r_soc_ciciec/fpga/project/ipgen/clk_pll/clk_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
